# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x05\x63loud\":\n\tChunkData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"/\n\x0c\x43hunkRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xab\x01\n\x0bStorageNode\x12/\n\nStoreChunk\x12\x10.cloud.ChunkData\x1a\x0f.cloud.Response\x12\x36\n\rRetrieveChunk\x12\x13.cloud.ChunkRequest\x1a\x10.cloud.ChunkData\x12\x33\n\x0b\x44\x65leteChunk\x12\x13.cloud.ChunkRequest\x1a\x0f.cloud.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKDATA']._serialized_start=24
  _globals['_CHUNKDATA']._serialized_end=82
  _globals['_CHUNKREQUEST']._serialized_start=84
  _globals['_CHUNKREQUEST']._serialized_end=131
  _globals['_RESPONSE']._serialized_start=133
  _globals['_RESPONSE']._serialized_end=177
  _globals['_STORAGENODE']._serialized_start=180
  _globals['_STORAGENODE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
